
<?php 
if(Mage::getStoreConfig('mw_cmspro/news/usingcomment')==1&&$this->getItem()->getAllowcomment()==1): ?>
<?php $_items = $this->getCommentCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):?>
        <h2><?php echo $this->__('Customer Comment') ?></h2>
        <?php echo $this->getChildHtml('toolbar') ?>
        <dl >
        <?php foreach ($_items as $_comment):?>
            <dt><h6><?php echo $this->__('Review by <span style="border-bottom:1px solid; "><i>%s</i></span>', $this->htmlEscape($_comment->getFullname())) ?><small class="date"><?php echo $this->__(' (Posted on %s)', $this->formatDate($_comment->getCreatedAt()), 'long') ?></small></h6>
            </dt>
            <dd>
                <?php $_votes = $_comment->getRatingVotes(); ?>
                <?php if (count($_votes)): ?>
                <table class="ratings-table">
                    <col width="1" />
                    <col />
                    <tbody>
                        <?php foreach ($_votes as $_vote): ?>
                        <tr>
                            <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif; ?>
                <p style="text-indent: 30px"><?php echo nl2br($this->htmlEscape($_comment->getContent())) ?></p>
                
            </dd>
			<br/>
        <?php endforeach; ?>
        </dl>
        <?php echo $this->getChildHtml('toolbar') ?>
    <?php endif;?>
    <?php echo $this->getChildHtml('comment_form') ?>
</div>
<?php endif;?>