<?php
//Mage::getSingleton('core/session')->unsetData('currency_session');Mage::getSingleton('core/session')->unsetData('foreigncustomer');die;
 //  vnip: 203.162.0.181   canadaip: 64.26.133.155 usip:66.249.71.117   real ip: $_SERVER['REMOTE_ADDR'] impotain 45.78.23.77	
if(Mage::getStoreConfig('ipchecker/info/enabled')){
$currency_session = Mage::getSingleton('core/session')->getCurrencySession();
	if(!isset($currency_session)){	 
					Mage::getSingleton('core/session')->setCurrencySession(1);
					Mage::getSingleton('core/session')->unsetData('foreigncustomer');
					$country=null;					
					$country=$this->getGeoip(); 
					//var_dump($country);die;
							$s=array();
							if(isset($country)&&$country[1]!='RD'){							
									$rules=unserialize(Mage::getStoreConfig('ipchecker/info/checksetup'));						
									$c=1;$s=null;
									foreach($rules as $rule){						
											if($rule['country']=='*') 
											$s=$rule;//Mage::log(explode(",",$rule['country']));die;
											if(in_array($country[1],explode(",",$rule['country']))){						
													$c=0;												
															Mage::app()->setCurrentStore($rule['storeview']);	
															Mage::app()->getCookie()->setStore($rule['storeview']);					
															Mage::app()->getCookie()->set('store',$rule['storeview'], true);		
															Mage::getSingleton('core/session')->setForeigncustomer(0);							
											};
										};
										if($c&&isset($s)){																			
													Mage::app()->setCurrentStore($s['storeview']);	
													Mage::app()->getCookie()->setStore($s['storeview']);							
													Mage::app()->getCookie()->set('store',$s['storeview'], true);													 Mage::getSingleton('core/session')->setForeigncustomer(1);
													
													/* Currency */
											/* if($mode=='1'||$mode=='3')
													Mage::app()->getStore()->setCurrentCurrencyCode($s['currnecy']); */				
										}elseif($c==1){
												Mage::getSingleton('core/session')->setForeigncustomer(1);
										};			
							}													
					
		}		
}
?>