

         <div class="wraper-about-us blog-id">
			     <div class="page-title">
			            <h1><?php echo $this->__('News & Updates');?></h1>
		         </div>
				
				<?php $posts = $this->getPosts(); ?>
				<?php foreach ($posts as $post): ?>
				<div class="postWrapper">
					 <div class="postTitle">
			    <h3><?php 
list($day, $time)= split(' ', $post->getCreatedTime());
echo $day; ?></h3>
						<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
					</div>
					<div class="postContent">
					
					     <?php echo $post->getPostContent(); ?>
						 <div class="blog-read-more"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $this->__('Read More');?></a></div>
					
					</div>
					
					
					  
				</div>
              

				<?php endforeach; ?> 
				<?php $this->getPages(); ?>
                <div style="height:1px;">&nbsp;</div>
		  </div>

