<div id="newsignupform">
	<form id="form-validate" method="post" action="<?php echo $this->getUrl("newsletter/subscriber/new")?>">
        <div class="fieldset">
            <input type="hidden" value="" name="success_url">
            <input type="hidden" value="" name="error_url">
            <div class="legend">
            	<span>Enter Your Contact Information</span>
            	<h4>Please fill out your contact information below to receive cytoskeleton news, and exciting offers.</h4>
            </div>
            <ul class="form-list">
                <li class="fields">
                    <div class="customer-name">
					    <div class="field name-firstname">
					        <label class="required" for="firstname"><em>*</em>First Name</label>
					        <div class="input-box">
					            <input type="text" class="input-text required-entry" maxlength="255" title="First Name" value="" name="firstname" id="firstname">
					        </div>
					    </div>
					    <div class="field name-lastname">
					        <label class="required" for="lastname"><em>*</em>Last Name</label>
					        <div class="input-box">
					            <input type="text" class="input-text required-entry" maxlength="255" title="Last Name" value="" name="lastname" id="lastname">
					        </div>
					    </div>
					</div>
                </li>
                <li>
	                <div style="padding-right:15px; clear: both;margin-bottom: 20px;">
	                    <label class="required" for="email_address"><em>*</em>Email Address</label>
	                    <div class="input-box">
	                        <input type="text" class="input-text validate-email required-entry" title="Email Address" style="width: 350px;" value="" id="email_address" name="email">
	                    </div>
	                </div>    
                    <div style="float:left; clear: both;">
		                <label class="required" for="company"><em>*</em>Company / Institution</label><br>
		                <div class="input-box">
						 	<input type="text" class="input-text required-entry" title="Company / Institutiony" style="width: 350px;" value="" id="company" name="company">
						</div>
					</div>
                    
                </li>
				<li>
                    <div>
                    	<label for="comment">Comment</label>
	                    <div class="input-box">
	                        <textarea rows="" cols="" style="width: 350px;" name="comment" id="comment"></textarea>
	                    </div>
                    </div>
                </li>
			</ul>
			<div class="buttons-set" style="background: #EFEFEF;">
	            <button class="button" title="Submit" type="submit"><span><span>Submit</span></span></button>
	        </div>
        </div>
    </form>
    <script type="text/javascript">
    	//<![CDATA[
        	var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
</div>