<?php
//{{block type="core/template" name="featured" as="featured" template="catalog/product/products.phtml}}

$categoryId = $this->getRequest()->getParam('id', false);
$totalPerPage = ($this->show_total) ? $this->show_total : 100;
$visibility = array(
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                  );

$storeId = Mage::app()->getStore()->getId();

$_productCollection = Mage::getResourceModel('reports/product_collection')
						->addAttributeToSelect('*')     
					        ->setStoreId($storeId)
                        ->addStoreFilter($storeId)	
					    ->addAttributeToFilter('visibility', $visibility)
						->addAttributeToFilter('products', true)
						->setOrder('name', 'asc')
						->addAttributeToSelect('status') 
						->addCategoryFilter(Mage::getModel('catalog/category')->load($categoryId))
						->setPageSize($totalPerPage);
Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($_productCollection);
Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($_productCollection);
Mage::getSingleton('catalog/product_visibility')->addVisibleInSearchFilterToCollection($_productCollection);


// // if product is part of configurable product get first parent product
// $junkProducts = new Varien_Data_Collection();
// foreach ($_productCollection as $k => $p) {
	// $p = $p->loadParentProductIds();
	// $parentIds = $p->getData('parent_product_ids');	
	// if (is_array($parentIds) && !empty($parentIds)) {
		// if (!$junkProducts->getItemById($parentIds[0])) {
			// $parentProduct = Mage::getModel('catalog/product')->setStoreId($storeId)->load($parentIds[0]);
			// if ($parentProduct->isVisibleInCatalog()) {
				// $junkProducts->addItem($parentProduct);
			// }
		// }
	// } else {
		// if (!$junkProducts->getItemById($k)) {
			// $junkProducts->addItem($p);
		// }
	// }		
// }
// $_productCollection = $junkProducts;
// //end if product is part of configurable product get first parent product
?>

<div id="category-table-container">
<?php $_collectionSize = $_productCollection->count() ?>
    <table cellspacing="0" class="products-grid-pd">
    <thead>
    <tr>
    	<th><?php echo $this->__('Product Description');?></th>
    	<th><?php echo $this->__('MSDS');?></th>
    	<th><?php echo $this->__('Datasheet');?></th>
    	<th><?php echo $this->__('Cat #');?></th>
    	<th><?php echo $this->__('Order');?></th>
    	</tr>
    </thead>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php if ($i++%1==0): ?>
    <tr>
    <?php endif ?>
	 		<td>
				<div class="bg_info_product">
				   <h5><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName());?></a></h5>
				</div>
			</td> 
			<td>
				<div class="pdf">
					<a href="<?php echo $_product->getMsds();?>"> 
						<img src='<?php echo $this->getSkinUrl('images/pdf.gif');?>'/>
					</a>
				</div>
			</td>
			<td> 
				<div class="pdf">
					<a href="<?php echo $_product->getManual();?>">
						<img src='<?php echo $this->getSkinUrl('images/pdf.gif');?>'/>
					</a>
				</div>
			</td>
			<td>
				 <div class="sku">
				     <?php echo $this->htmlEscape($_product->getCat()) ?>
				 </div>
			</td>
			<td>
				<div class="addtocart">
				   <a title="Add to cart" href="<?php echo $_product->getProductUrl()?>" class="button ajax_add_to_cart_button exclusive"><img src="<?php echo  $this->getSkinUrl('images/cart.gif');?>"/></a>
				  </div>  
			</td>
	 
	
    <?php if ($i%1==0 && $i!=$_collectionSize): ?>
    </tr>
    <?php endif ?>
    <?php endforeach ?>
    <?php for($i;$i%1!=0;$i++): ?>
          <td class="empty-product">&nbsp;</td>
    <?php endfor ?>
    <?php if ($i%1==0): ?>
    </tr>
    <?php endif ?>
    </table>
    <script type="text/javascript">decorateTable('product-list-table')</script>
</div>


