<?
/*add multi product to cart by cat(cat is new custom attribute of product, cat is unique like sku)
 *28/09/2011
 *add to cart by sku instead of cat
 *allow add to cart by sku of custom options
 *@author: Chuongnh
 */
 ?>
<script type="text/javascript"> 
function quickaddtocart() {
	var sku= '';
	var qty = '';
	var i;
	for(i=1; i<=5; i++){
		sku+= ($('sku'+i).value).strip();
		qty += ($('qty'+i).value).strip();
		if( i!=5 ){
			sku+= ',';
			qty += ',';
			}
	}
	var url = document.URL + '?products='+sku+'&qty='+qty;
	window.location.href = url;
}
</script>


   
	   <div class="wraper-about-us gdkl">
			
				
				<div class="page-title">
			         <h1><?php echo $this->__('Quick Order');?></h1>
		        </div>
				<div class="content-about-us">
					<p class="q-o"><?php echo $this->__('The Quick Order form is intended for our customers who prefer to shop directly by using product Cat#.');?></p>
					<p class="quantity-s"><?php echo $this->__('Enter the Cat# and quantity to order product(s) and then click on add to cart.');?></p>
					
					 <div class="Quick-order" width="269">
					 
						<!--<div class="Cat">
						    <h2><?php echo $this->__('Cat #');?></h2>
						</div>
						<div class="Quantity-v">
						    <h2> <?php echo $this->__('Quantity');?></h2>
						</div>-->
						<!--<div class="clear-both">
						   <span><label></label></span>
						</div>-->
					 
						<table width="269" cellspacing="2" cellpadding="2" class="quick-order2">
							<tr>
							<td>
								<div class="Cat td-order1">
								<h2><?php echo $this->__('Cat #');?></h2>
								</div>
							</td>
							<td>
							<div class="Quantity-v td-order2">
						    <h2> <?php echo $this->__('Quantity');?></h2>
						</div>
							</td>
							</tr>
							<tr>
							   <td class="td-order1"><input class="order-text" type="text" name="sku1" id="sku1"/></td>
							   <td class="td-order2"><input class="order-qty" type="text" name="qty1" id="qty1"/></td>
							</tr>
							<tr>
							   <td class="td-order1"><input class="order-text" type="text" name="sku2" id="sku2"/></td>
							   <td class="td-order2"><input  class="order-qty" type="text" name="qty2" id="qty2"/></td>
							</tr>
							<tr>
							   <td class="td-order1"><input class="order-text" type="text" name="sku3" id="sku3"/></td>
							  <td class="td-order2"><input class="order-qty" type="text" name="qty3" id="qty3"/></td>
							</tr>
							<tr>
							     <td class="td-order1"><input class="order-text" type="text" name="sku4" id="sku4"/></td>
								 <td class="td-order2"><input  class="order-qty" type="text" name="qty4" id="qty4"/></td>
							</tr>
							<tr>
							   <td class="td-order1"><input class="order-text" type="text" name="sku5" id="sku5"/></td>
							   <td class="td-order2"><input  class="order-qty" type="text" name="qty5" id="qty5"/></td>
							</tr>
						</table>
						
						<div class="d">
							<button onclick="quickaddtocart()" class="button btn-cart " title="Add to Cart" type="button"><span><span>Add to Cart</span></span></button>
						</div>
					 </div>
				</div>
		 </div>



<?php 
/*include_once 'app/Mage.php';
Mage::app();
Mage::getSingleton('core/session', array('name' => 'frontend'));*/

$session = Mage::getSingleton('checkout/session');
//$helper = Mage::helper('core');
if($this->getRequest()->getParam('products'))
    	{
	    	$params['sku'] = explode(',', $this->getRequest()->getParam('products'));
	 		$params['qty'] = explode(',', $this->getRequest()->getParam('qty'));
	 		$cart = Mage::getModel('checkout/cart');
			$cart->init();
	 		$qtySum = 0;
	 		
			for ($i=0;$i<=5;$i++) 
			{
				//get id from sku
				if ($params['sku'][$i] == '') continue;
				$pId = null;
				$productModel = Mage::getModel('catalog/product');
				$pId = $productModel->getIdBySku($params['sku'][$i]);
				
				if(!$pId){
					//if requested sku is belong to a custom options
					$customOptions = array();
					$conn = Mage::getModel('core/resource')->getConnection();
			 		$customOptionArray = $conn->fetchAll("SELECT option_id,option_type_id FROM catalog_product_option_type_value WHERE sku = '".$params['sku'][$i]."'");
			 		foreach ($customOptionArray as $option)
			 		{
			 			$customOptions[$option['option_id']] =  $option['option_type_id'];
			 			$productId = $option['option_id'];
			 		}
			 		$optionIdArray = array_keys($customOptions);
			 		$pId = $conn->fetchOne("SELECT product_id FROM catalog_product_option WHERE option_id = '".$optionIdArray[0]."'");
			 		//Zend_Debug::dump($pId);die;
				}
	 			
	 			if($pId)
				{ 
					$product = $product = $productModel->setStoreId(Mage::app()->getStore()->getId())->load($pId);
					//$product->setStoreId(Mage::app()->getStore()->getId())->load($pId);
					if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE) 
					{
						try 
						{   
							//if simple product belong to configurable product
							$configurableProduct = Mage::getModel('catalog/product_type_configurable');
							$parentIdArray = $configurableProduct->getParentIdsByChild($product->getId());
						    if (!empty($parentIdArray))
						    {
						        $parentProduct = Mage::getModel('catalog/product')->load($parentIdArray[0]);
							    if($parentProduct->getTypeId() == 'configurable' )
								{
									
									//get configurable attributes of the parent
							        $tempattr = $parentProduct->getTypeInstance()->getConfigurableAttributesAsArray();
									$options = array();
							        foreach ($tempattr as $attr)
							        {    
							            //save in set
										$options[$attr['attribute_id']] = $product->getData($attr['attribute_code']);
							        }
									$product = $parentProduct;
									$pId = $parentIdArray[0];
								 }
						    }
							//$cart->addProduct($product, array('product'=> $pId,'qty' => $params['qty'][$i],'super_attribute' => $options));
							$cart->addProduct($product, array('product'=> $pId,'qty' => $params['qty'][$i],
																'super_attribute' => $options,
																'options' => $customOptions));
						    //calculate total product added
						    //if quantity is not valid (negative number or 0,NaN)then set quantity to 1
							if(is_numeric($params['qty'][$i]) && $params['qty'][$i]>= 0)
							{
								$qtySum += $params['qty'][$i];
							}else $qtySum += 1;
							
						}
						
						catch (Exception $e) {
							$session->addError($this->__('Error adding product with cat = %s. %s',$params['sku'][$i], $e->getMessage()));
						continue; }
					}else
					{
						$session->addError($this->__('Product with cat = %s is not a simple product. So it can not be added to cart',$params['sku'][$i]));
					}
				}else 
				{	
					$session->addError($this->__('Not found product with cat = %s',$params['sku'][$i]));
				}
			}
			$cart->save();
			//Mage::getSingleton('checkout/session')->setCartWasUpdated(true);
	 
			if ($this->getRequest()->isXmlHttpRequest()) {
				exit('1');
			}
	 		$session->addSuccess($this->__('%d item(s) was added to shopping cart.',(int)$qtySum));
			echo "<script type='text/javascript'>window.location.href ='".Mage::getUrl('checkout/cart')."'</script>"; 
		}

?>
