<?php if (!Mage::registry('current_category')) return ?>
    
    <?php $_categories =$this->getCurrentChildCategories() ; 
    $_category =Mage::registry('current_category'); 
    $currentCategoryId = $_category->getId();
    $currentCategoryUrl = $_category->getUrl();
?>
<script>
  window.onload = function() {
    var categoryId="<?php echo $currentCategoryId;?>";
   getval(categoryId,"ASC","name");
}
</script>
<select name="category_filter" id="cat_filter" onchange="location = this.options[this.selectedIndex].value;">   
    <option data-id="<?php echo $currentCategoryId ?>" value="<?php echo $_category->getUrl()?>">Filter By Subcategory...</option>    
    <?php foreach ($_categories as $_category): ?>       
        <?php if($_category->getIsActive()): ?>
        <option value="<?php echo $_category->getUrl()?>" data-id="<?php echo $currentCategoryId ?>">
        <?php echo $this->htmlEscape($_category->getName()) ?></option>
        <?php endif; ?>
    <?php endforeach ?> 
</select>
<div id ="category-table-container">
    <table cellspacing="0" class="products-grid-pd" id="category-table">    
        <thead>
            <tr>
                <th>
                    <?php echo $this->__('Product Description');?>
                    <div class="arrow">
                        <img class="ascending" data-dir="DESC" data-attribute-name="name" src="<?php echo
                        $this->getSkinUrl("images/decending.png")?>" alt="ascending"/>
                        <img class="decending" data-attribute-name="name" data-dir="ASC" src="<?php echo
                        $this->getSkinUrl("images/ascending.png") ?>" alt="decending"/>
                    </div>
                </th>
                <th>
                    <?php echo $this->__('Type');?>
                    <div class="arrow">
                        <img class="ascending" data-attribute-name="type" data-
                        dir="DESC" src="<?php echo $this->getSkinUrl("images/decending.png")?>"
                        alt="ascending"/>
                        <img class="decending" data-attribute-name="type" data-
                        dir="ASC" src="<?php echo $this->getSkinUrl("images/ascending.png") ?>"
                        alt="decending"/>
                    </div>
                </th> 
                <th>
                    <?php echo $this->__('Cat#');?>
                    <div class="arrow">
                        <img class="ascending"
                        data-attribute-name="cat" data-dir="DESC" src="<?php echo
                        $this->getSkinUrl("images/decending.png")?>" alt="ascending"/>
                        <img
                        class="decending" data-attribute-name="cat" data-dir="ASC" src="<?php echo
                        $this->getSkinUrl("images/ascending.png") ?>" alt="decending"/>
                    </div>
                </th>
                <th><?php echo $this->__('View');?></th>
            </tr>
        </thead>
        <tbody>
        </tbody>   
    </table> 
</div> 
<script type="text/javascript">

function getval(categoryId,dir,sortby)
{
    var url="<?php echo Mage::getUrl('categoryfilter/index/loadcategoryproduct');?>";
    jQuery.ajax({
                    type: "POST",
                    url :url,
                    data:{'id':categoryId,'dir':dir,'sortby':sortby},
                    success:function(response){
                        jQuery("#category-table tr:gt(0)").remove();                           
                        var data = jQuery.parseJSON(response);
                        jQuery.each(data,function(key, item) {
                            var tr =createColumnFields(item.name,item.type,item.category,item.view);
                            jQuery("#category-table tbody").append(tr);
                           
                        });
                    }   
                });
}
function createColumnFields(desc,type,cat,view) 
{
    var tr = '<tr>' ;
    // create a new Label Text
    tr += '<td><a href="' + view + '">' + desc  + '</a></td>';
    tr += '<td>' + type + '</td>';
    tr += '<td>' + cat  + '</td>';
    tr += '<td><a href="' + view + '"><img src="<?php echo  $this->getSkinUrl('images/cart.png');?>"/></a></td>';  
    tr +='</tr>';
    return tr;
}

jQuery(".arrow .decending").click(function(){
    jQuery(this).parent().addClass('active');
    jQuery(".arrow.active .decending").hide();
    jQuery(".arrow.active .ascending").show();
     var categoryId= "<?php echo $currentCategoryId;?>";
    var direction = this.getAttribute("data-dir");
    var sortby = this.getAttribute("data-attribute-name");
    getval(categoryId,direction,sortby);
    jQuery(this).parent().removeClass('active');
});
jQuery(".arrow .ascending").click(function(){
    jQuery(this).parent().addClass('active');
    jQuery(".arrow.active .decending").show();
    jQuery(".arrow.active .ascending").hide();
    var categoryId= "<?php echo $currentCategoryId;?>";
    var direction = this.getAttribute("data-dir");
    var sortby = this.getAttribute("data-attribute-name");
    getval(categoryId,direction,sortby);
    jQuery(this).parent().removeClass('active');
});

</script>
