
<?php if (!Mage::registry('current_category')) return ?>
<?php $_categories = $this->getCurrentChildCategories() ?>

<ul>
<?php foreach ($_categories as $_category): ?>
	<?php if($_category->getIsActive()): ?>
	<li>
		<a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="current"<?php endif; ?>>
			<?php echo $this->htmlEscape($_category->getName()) ?>
		</a>
	</li>
	<?php endif; ?>
<?php endforeach ?>
</ul>
           

