
<?php $deeplevel = Mage::getStoreConfig("mw_cmspro/left_menu_category/deeplevel"); ?> 
<?php $allows1 = Mage::getStoreConfig("mw_cmspro/left_menu_category/rightmenu"); ?>
<?php
	$current_cat_id = $current_cat_id = (isset($_SESSION['cmspro_current_cat'])) ? $_SESSION['cmspro_current_cat'] : "";
	if($current_cat_id){
    		$root_path = Mage::getModel('cmspro/category')->load($current_cat_id)->getRootPath();
    		$root_path = explode('/',$root_path);
        	if(sizeof($root_path)>2){$current_cat_id = $root_path[1];}else{$current_cat_id="";}
    	}
?>
<?php if($allows1==1  && (Mage::getModel('cmspro/category')->getMainCategories()->count()>0)):?>
<?php if(Mage::getStoreConfig('mw_cmspro/left_menu_category/collapse')==true ):?>
<div id="mv_smartmenu_news">
	<div class="mv_smartmenu">
		<div class="mv_smartmenu_head">
			<h4><a href="<?php echo Mage::getBaseUrl().$this->_getRootURL(); ?>"><?php echo $this->_getRootName(); ?></a></h4>
		</div>
		<div class="mv_smartmenu_content">
			
			<ul id="newsMenu_acc">			
			<?php
			$_main_categories=Mage::getModel('cmspro/category')->getMainCategories();
			$i=0;
			foreach ($_main_categories as $_main_category):	
			?>
				<?php 
				$_sub_categories = $_main_category->getChildren();
				foreach ($_sub_categories as $_sub_category):
				?>
				<li <?php if($i==0):?>class="first"<?php endif;?>>
					<a class="left main-cate" href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub_category->getUrlRewriteId())->getRequestPath();?>">
						<?php echo $_sub_category->getName()?>
					</a>
					<?php if(($_sub_category->hasChildren()) && ($deeplevel!=2)):?>
					<span class="right head <?php echo ($_sub_category->getCategoryId()==$current_cat_id) ? "selected":""; ?>">
						<a href="javascript:;"></a>
					</span>
					<div class="mw-duc" style="<?php echo ($_sub_category->getCategoryId()!=$current_cat_id) ? "display:block !important":""; ?>"></div>
					<?php endif;?>
					<ul style="clear:both;<?php echo ($_sub_category->getCategoryId()==$current_cat_id) ? "display:block;":""; ?>" >
						<li style="display:none;"></li>
						<?php 
						$_sub3s = $_sub_category->getChildren(); 
						foreach ($_sub3s as $_sub3):
						if($deeplevel==2): break;  endif;?>
						<li>
							<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub3->getUrlRewriteId())->getRequestPath();?>">
								<?php echo $_sub3->getName()?>
							</a>
							<ul style="clear:both;" >
								<li style="display:none;"></li>
								<?php 
								$_sub4s = $_sub3->getChildren(); 
								foreach ($_sub4s as $_sub4):
								if($deeplevel==3): break;  endif;?>
								<li>
									<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub4->getUrlRewriteId())->getRequestPath();?>">
										<?php echo $_sub4->getName()?>
									</a>
									<ul style="clear:both;" >
										<li style="display:none;"></li>
										<?php 
										$_sub5s = $_sub4->getChildren(); 
										foreach ($_sub5s as $_sub5):
										if($deeplevel==4): break;  endif;
										?>
										<li>
											<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub5->getUrlRewriteId())->getRequestPath();?>">
												<?php echo $_sub5->getName()?>
											</a>
										</li>
									   <?php endforeach;?>
									</ul>
								</li>
							   <?php endforeach;?>
							</ul>
						</li>
					   <?php endforeach;?>
					</ul>
				<div class="clear"></div>	
				</li>
				<?php $i++; ?>
				 <?php endforeach;?>
					
			<?php
			endforeach;
			?>
<!--		<div class="clear"></div>-->
		</ul>
		</div>		
	</div>
	<div class="cmspro_clear "></div>
</div>
	<?php else: ?>
<div id="mv_smartmenu_news">		
	<div class="mv_smartmenu">
		<div class="mv_smartmenu_head">
			<h4><a href="<?php echo Mage::getBaseUrl().$this->_getRootURL(); ?>"><?php echo $this->_getRootName();  ?></a></h4>
		</div>
		<div class="mv_smartmenu_content">
			<ul id="cate_collap">
			<li style="display:none;"></li>
			<?php
			//$_main_categories=$this->getsMainCategories(Mage::getStoreConfig('mw_cmspro/left_menu_category/toplevel'));
			$_main_categories = Mage::getModel('cmspro/category')->getMainCategories();
			$i=0;
			foreach ($_main_categories as $_main_category):?>	
			
				<?php 
				$_sub_categories = $_main_category->getChildren(); 
				foreach ($_sub_categories as $_sub_category):
				?>
				<li <?php if($i==0):?>class="first"<?php endif;?> style="clear: both; float: left; width:100%;">
					<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub_category->getUrlRewriteId())->getRequestPath();?>">
						<?php echo $_sub_category->getName()?>
					</a>
					<?php if(($_sub_category->hasChildren()) && ($deeplevel!=2)): ?>					
						<a class="title_collap" href="#" onclick="return false;"><span class="right head">&nbsp;</span> </a>
					<?php endif;?>
					<ul style="margin-left: 10px; clear:both;" >
						<li style="display:none;"></li>
						<?php 
						$_sub3s = $_sub_category->getChildren(); 
						foreach ($_sub3s as $_sub3):
						if($deeplevel==2): break;  endif;?>
						<li>
							<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub3->getUrlRewriteId())->getRequestPath();?>">
								<?php echo $_sub3->getName()?>
							</a>
							<ul style="margin-left: 10px; clear:both;" >
								<li style="display:none;"></li>
								<?php 
								$_sub4s = $_sub3->getChildren(); 
								//if(sizeof($_sub4s->getData())>0){
								foreach ($_sub4s as $_sub4):
								if($deeplevel==3): break;  endif;?>
								<li>
									<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub4->getUrlRewriteId())->getRequestPath();?>">
										<?php echo $_sub4->getName()?>
									</a>
									<ul style="margin-left: 10px; clear:both;" >
										<li style="display:none;"></li>
										<?php 
										$_sub5s = $_sub4->getChildren(); 
										
										foreach ($_sub5s as $_sub5):
										if($deeplevel==4): break;  endif;
										?>
										<li>
											<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($_sub5->getUrlRewriteId())->getRequestPath();?>">
												<?php echo $_sub5->getName()?>
											</a>
										</li>
										<?php endforeach;?>
									</ul>
								</li>
								<?php endforeach;?>
									
							</ul>
						</li>
						<?php endforeach;?>
					</ul>
				</li>
				<?php endforeach;?>
			</li>
			<?php
			$i++;
			endforeach;
			?> 
		</ul>
		</div>		
	</div>
	<div class="cmspro_clear "></div>
</div>

<?php endif;?>		
<?php endif;?>