<?php $categories = (Mage::getModel('cmspro/category')->getRootCategory());?>
<ul id="nav">
	<li><a href="<?php echo $this->getUrl('');?>"><?php echo $this->__('Home');?></a></li>
	<li onmouseout="toggleMenu(this,0)" onmouseover="toggleMenu(this,1)" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
		<a href="#"><?php echo $this->__('Products');?></a>
		<ul>
			<?php $_main_categories=$this->getStoreCategories();
			$i=0;
			foreach ($_main_categories as $_main_category):	
			if ($_main_category->getIsActive()) {?>	
				<li class="<?php if($i==0): echo 'first'; endif;?>">
					<a href="<?php echo $this->getCategoryUrl($_main_category)?>">
						<span>
							<?php echo $_main_category->getName()?>
						</span>
					</a>
				</li>
			<?php }
			$i++;
			endforeach;
			?>
		</ul>
	</li>
	<li>
		<a href="<?php echo $this->getUrl('info-resources');?>"><?php echo $this->__('Info Resources');?></a>
		<ul>
			<li class="first"><a href="<?php echo $this->getUrl('manuals');?>"><span><?php echo $this->__('Manuals');?></span></a></li>
			<li><a href="<?php echo $this->getUrl('msds');?>"><span><?php echo $this->__('MSDS');?></span></a></li>
			<li><a href="<?php echo $this->getUrl('faqs');?>"><span><?php echo $this->__('FAQs');?></span></a></li>
			<li><a href="<?php echo $this->getUrl('technical-tips');?>"><span><?php echo $this->__('Technical Tips');?></span></a></li>
			<li><a href="<?php echo $this->getUrl('technical-support');?>"><span><?php echo $this->__('Technical Support');?></span></a></li>
		</ul>
	</li>
	<li><a href="<?php echo $this->getUrl('distributors');?>"><?php echo $this->__('Distributors');?></a></li>
	<li>
		<a href="<?php echo $this->getUrl('about-us');?>"><?php echo $this->__('About Us');?></a>
		<ul>
			<li class="first"><a href="<?php echo $this->getUrl('contacts');?>"><span><?php echo $this->__('Contact Us');?></span></a></li>
			<li><a href="<?php echo $this->getUrl('company-history');?>"><span><?php echo $this->__('Company History');?></span></a></li>
			<li><a href="<?php echo $this->getUrl('careers');?>"><span><?php echo $this->__('Careers');?></span></a></li>
		</ul>
	</li>
	
	<!-- Start adding News Categories of Cms pro-->
	<?php 
	$current_cat_id = (isset($_SESSION['cmspro_current_cat'])) ? $_SESSION['cmspro_current_cat']:"";
		$current_cat_id = (($this->getRequest()->getParam('id')) && ($this->getRequest()->getModuleName()=="cmspro") && ($this->getRequest()->getControllerName()=="category")) ? $this->getRequest()->getParam('id') : $current_cat_id;
		$news_current = ($this->getRequest()->getModuleName()=="cmspro") ? true:false;
        // News Category menu
        $a = (Mage::getStoreConfig('mw_cmspro/left_menu_category/enable')) ? Mage::getStoreConfig('mw_cmspro/left_menu_category/enable'):"";
        if($a=="1"){
			if(Mage::getStoreConfig('mw_cmspro/left_menu_category/show_root_category')=="1"){
				$root_menu = Mage::getModel('cmspro/category')->load(1);
        ?>
		        <li class="about level0 nav-1 parent <?php echo ($news_current) ? "active":""; ?>" onmouseout="toggleMenu(this,0)" onmouseover="toggleMenu(this,1)">
		        	<a href="<?php echo Mage::getBaseUrl().$root_menu->_getUrlRewrite() ?>"><?php echo $root_menu->getName() ?></a>
		        	<ul class="level0">
		        		<?php
							foreach($categories as $cat){
								echo Mage::getModel('cmspro/category')->drawItem($cat);
							}
		        		?>
		        	</ul>
		        </li>
        	<?php 
			}else{
				foreach($categories as $cat){
					echo Mage::getModel('cmspro/category')->drawItem($cat,0,false,$current_cat_id);
				}
        	} 
		}?>
	
	
	
	<!-- End News Categories of Cms pro-->
	
	
</ul>