<div class="page-title">
    <h1><?php echo $this->__('International Order Request Form') ?></h1>
</div>
<div >
    <p class="getdescription"><?php echo $this->getDescription(); ?></p>
</div>
<div class="class-required"> <label class="required"><em>*</em>required fields</label></div>  
<div class="requeist-top"></div>
<div class="requeist-center">
 <div class="requeist-center-info">
	<form action="<?php echo $this->getUrl('emailorderforforeign/index/submit') ?>" method="post" id="mw_eoff_order_request_form" enctype="multipart/form-data">
		<div class="fieldset">
			<ul class="form-list">
				<li class="fields">
					<div class="field">
						
						<div class="input-box">
						    <label class="required"><em>*</em><?php echo $this->__('Your Name'); ?></label>
							<input name="customer_name" id="mw_efof_name" value="" class="input-text required-entry" type="text"/>
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						
						<div class="input-box">
						    <label class="required"><em>*</em><?php echo $this->__('Company/Institution'); ?></label>
							<input name="company" id="mw_efof_company" value="" class="input-text required-entry" type="text"/>
						</div>
					</div>

				</li>
				<li class="fields">
					<div class="field">
						
						<div class="input-box">
						    <label class="required"><em>*</em><?php echo $this->__('Country'); ?></label>
							<input name="country" id="mw_efof_country" value="" class="input-text required-entry" type="text"/>
						</div>
					</div>

				</li>
				<li class="fields">
					<div class="field">
						
						<div class="input-box">
						    <label class="required"><em>*</em><?php echo $this->__('Email'); ?></label>
							<input name="email" id="mw_efof_email" value="" class="input-text required-entry validate-email" type="text"/>
						</div>
					</div>

				</li>
				<li class="fields">
					<div class="field">
						
						<div class="input-box">
						    <label class="required"><em>*</em><?php echo $this->__('Phone'); ?></label>
							<input name="phone" id="mw_efof_phone" value="" class="input-text required-entry" type="text"/>
						</div>
					</div>

				</li>
				<script type="text/javascript">
					var selectIds = new Array();
				</script>    
				<?php for ($index = 1; $index <= Mage::getStoreConfig('emailorderforforeign/general/allowed_product_total'); $index++): ?>
					<li class="select-requiet">
					    <div class="select-option-requiet">
							<!--<div class="select-option-requiet-av"><select id="mw_efof_category_<?php echo "$index"; ?>" style="width: 200px">
								<?php //echo $this->getOptionsHtml(); ?>
							</select></div>
							<select id="mw_efof_product_<?php //echo "$index"; ?>" name="order[<?php //echo "$index"; ?>][sku]" style="width: 200px">
							</select>
							<script type="text/javascript">
								selectIds.push('mw_efof_category_'+'<?php echo $index ?>') ;
							</script>-->
							
							<select id="mw_efof_product_<?php echo "$index"; ?>" name="order[<?php echo "$index"; ?>][sku]" style="width: 200px">
								<?php echo $this->getOptionsHtml(); ?>
							</select>
							<label style="float:none"><?php echo $this->__('Qty'); ?></label>
							<input id="mw_efof_quantity" name="order[<?php echo "$index"; ?>][qty]" style="width: 40px" class="validate-number"></input>
						</div>
						 <div class="clear-both"></div> 
					</li>
				<?php endfor; ?>
				<li class="fields fields-textarea">
					
					<div class="input-box">
					    <label ><?php echo $this->__('Comment'); ?></label>
						<textarea class="textarea" cols="15" rows="2" style="width: 100%; height: 150px;" title="Content" name="content" id="mw_efof_comment"></textarea>
					</div>
				</li>
			</ul>
		</div>
		<div class="buttons-set">
			<button type="submit" class="button-ag"><span><span><?php echo $this->__('Submit Order Request'); ?></span></span></button>
		</div>
	</form>
  </div>
  <div class="clear-both"></div> 
</div>
<div class="requeist-bottom"></div>


<script type="text/javascript">
	var dataForm = new VarienForm('mw_eoff_order_request_form', true);
	
 //   document.observe("dom:loaded", function() {
//        for(index = 0; index <= selectIds.length; index ++){
//            Event.observe(selectIds[index], 'change', changeCategory);
//        }
//    });
 //   var repository = new Hash();
//    var url = '<?php echo Mage::getUrl('*/*/getProductInCategory');?>';
//    function changeCategory(event){
//        element = event.element();
 //       value = element.getValue();
//        id = element.identify();
//        index = id.substring(17);
//        $('mw_efof_product_'+ index).update('');
 //       if(repository.get(value) == undefined){
 //           new Ajax.Request(url,{
 //               method: 'post',
 //               parameters: {id: value},
 //               onSuccess: function(response){
 //                   repository.set(value , response.responseText);
 //                   $('mw_efof_product_'+ index).update(response.responseText);
 //               }
 //           });
 //       }else{
 //           option = repository.get(value);
 //           $('mw_efof_product_'+ index).update(option);
 //       }
  //  }
</script>

